### ISSUE TITLE
Create a mysql database using docker

### ISSUE THREAD

**Issue by KingsleySepeng** [KingsleySepeng/OnlineShop#3]

**Comment by KingsleySepeng** [comment]
```
docker compose up
```

```
docker compose down
```
```
mysql -u root -p 
```

**Comment by KingsleySepeng** [comment]
spring.datasource.url = jdbc:mysql://172.21.0.2:3306/user-service-db

**Comment by KingsleySepeng** [comment]
```
version: '3.8'

services:
  spring-user-service:
    container_name: spring-user-container
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx512m"
    depends_on:
      - mysql-db
    # networks:
    #   - spring-user-service-mysql-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service-db
    volumes:
      # - mysql-data:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
      # - ./user-service.sql:/docker-entrypoint-initdb.d/user-service.sql
    ports:
      - "3306:3306"
    networks:
      my-network:
        ipv4_address: 172.21.0.2
  
  networks:
    my-network:
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.0/16

# volumes:
#   mysql-data:
# networks:
#   spring-user-service-mysql-network:
#     driver: bridge
#     name: service-mysql-network
```
I am working on a way to specify a static ip address for the database.
